# Sharpmake AppVeyor CI configuration

image:
- Visual Studio 2017
- macOS

skip_commits:
  files:
    - docs/*

platform:
- Any CPU

configuration:
- Debug
- Release

before_build:
- cmd: bootstrap.bat
- sh: ./bootstrap.sh

build_script:
  - cmd: CompileSharpmake.bat Sharpmake.sln "%CONFIGURATION%" "%PLATFORM%"
  - sh: ./CompileSharpmake.sh Sharpmake.sln "${CONFIGURATION}" "${PLATFORM}"

test:
  assemblies:
    - 'Sharpmake.UnitTests\bin\*\Sharpmake.UnitTests.dll'

after_test:
- cmd: python regression_test.py
